### ISSUE TITLE
FingerJetFX Minutiae Counts Change Between Runs

### ISSUE THREAD

**Issue by gfiumara** [usnistgov/NFIQ2#13]
The feature `FingerJetFX_MinutiaeCount` can change between subsequent runs with the same binary on the same or different machines. +/- 5 minutia observed in most recent test on SD-29. This in turn changes `FingerJetFX_MinCount_COMMinRect200x200`, `FJFXPos_Mu_MinutiaeQuality_2`, `FJFXPos_OCL_MinutiaeQuality_80`, and ultimately `NFIQ2 score`.

This may be more suited as a bug in [FingerJetFXOSE](https://github.com/FingerJetFXOSE/FingerJetFXOSE), but needs to be addressed as part of NFIQ2.

**Comment by gfiumara** [comment]
This appears to exist in the shipping version of NFIQ2 as well.

**Comment by RLessmann** [comment]
Correct, we addressed this in the revised version of NFIQ2. Some code of FingerjetFXOSE was wrongly optim ized by different compilers.

**Comment by gfiumara** [comment]
The issue is still present in the code from #8. Is the zip file of FingerJetFXOSE code downloaded by the CMake file the most current version? I've just reproduced this again this morning on CentOS 7 with SD-29.

**Comment by RLessmann** [comment]
Not quite true, as you see we apply a diff within the NFIQ2 cmake process which patches the downloaded Fingerjet. So if you wanna no how to solve it, take a look to the diff.

**Comment by gfiumara** [comment]
Ah, I see. I am operating in an offline environment. I downloaded the packages on a different machine and brought them to the offline build/test machine, and unzipped the file after making a directory called "download" for each of the three external sources. By doing that, the patch step in fingerjetfxose's CMakeLists.txt is skipped. This needs to be fixed. I'll patch manually and retest.

**Comment by RLessmann** [comment]
In an offline scenario put the 3rd party packages somewhere and let cmake copy from your internal location.
But agreed, needs to be mentioned in the readme

**Comment by gfiumara** [comment]
So far, I am seeing stability in the FingerJet-based features between runs after applying the patch, at least on Linux with 3 different Intel CPU revisions. This gives me higher condifence that the issue is resolved, though I will continue to test on Mac, etc. I will close this issue and make another to track corrections and/or documentation to CMake such that the patch gets applied when the build is happening in an offline environment.
